spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    datasource:
      url: jdbc:mysql://localhost:3306/testdb
      username: pratap
      password: pratap